apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/ibnummuhammad/helloworld-nodejs
          env:
            - name: TARGET
              value: "Node.js Sample v1"
